### PR TITLE
chore: simplify code usage

### PR DESCRIPTION
**Pull request by Hengyu**
## Summary

1. use `let` to take value and return, in one line
2. add missing unit test

## Testing

Unit test

### CODE REVIEW

**Review by simeng-li — APPROVED** [review]
LGTM. 
Cheers~ Looking forward for more contributions

**Comment by simeng-li** [comment]
cc: @xiaoyijun

**Review by xiaoyijun — APPROVED** [review]
LGTM
Thanks~ :)

**Comment by Hengyu** [comment]
just wondering, why merge `master` into this branch.
if we want to keep this branch into latest version, we may also try `git rebase` :)

**Comment by simeng-li** [comment]
> just wondering, why merge `master` into this branch. if we want to keep this branch into latest version, we may also try `git rebase` :)

good call, it was auto generated by github `update_branch` action, as we enabled the up to date rule.  Feel free to rebase -> commit and merge

**Comment by Hengyu** [comment]
Got it, let me rebase and push again. 
Also, I'm not authorized to merge the PR.

**Comment by xiaoyijun** [comment]
Sorry, the github-action should be excute on pull request. We will update this later.

**Comment by Hengyu** [comment]
No problems 👍

**Comment by xiaoyijun** [comment]
@Hengyu 
The base branch requires all commits to be signed. 
One more thing, need to change the branch name in the pattern like `name–some-feature` (eg. hengyu-chore-simplify-code-usage`)
Thank you~

**Comment by Hengyu** [comment]
Renaming branch cause the Github automatically close the PR

**Comment by xiaoyijun** [comment]
A new pr is welcomed ~

**Comment by xiaoyijun** [comment]
try to pr with a new branch name 😄

**Pull request closed without merging**
